export class Requirements {
  id
  createddate
  creatorid
  creator
  title
  stateid
  state
  statetype
  laststateid
  laststate
  lastactiondate
  agentactions
  notactiveemails
  createdmonth
  displayname
  statetypename
  idworkflow
  workflow
  organization
  fechafin_real
  type
  typeid
  typepath
  description
  sprintid
  sprint
  onlysave
  createddateshort
  calendarid
  calendar
  wkfstates
  loggeduserrols
  application
  applicationid
  module
  moduleid
  requestdate
  requestedbyuser
  requestedbyuserid
  businessprocess
  requirementtype
  requirementtypeid
  mainobject
  mainobjectid
  priority
  priorityid
  estimatedstartdate
  estimatedenddate
  region
  area
  areaid
  workareaid
  workarea
  systemeffortinhours
  usereffortinhours
  previousstates
  project_id
  project
  businessprocessid
  regionid
  management_area_in_charge
  management_area_in_charge_id
}